- name: create new openstack networks
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/openstack_vars.yaml

  tasks:
  -  name: create networks
     os_network:
       cloud: mycloud
       state: present
       name: ext_network
       external: true
