- name: Deploy multiple instances on OpenStack
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/openstack_vars.yaml

  tasks:
  - name: deploy instances
    os_server:
       #auth:
         #auth_url: http://10.9.65.102:5000/v2.0
         #username: tenant1
         #password: Passw0rd
         #project_name: tenant1
       cloud: "{{ cloud_tenant }}"
       state: present
       name: "{{ instance_name }}{{ item }}"
       image: "{{ image }}"
       key_name: "{{ key_name }}"
       timeout: 200
       flavor: "{{ flavor }}"
       auto_ip: no
       nics:
         - net-name: "{{ network }}"
    register: newnodes
    with_sequence:
       count="{{ instance_count }}"

  - debug:
      var: newnodes
  
#  - add_host:
#       name: "{{ item.server.name }}"
#       groups: "{{ group }}"
#       ansible_host: "{{item.server.private_v4}}"
#       ansible_user: cloud-user
#       ansible_become: true
#    with_items: "{{ newnodes.results }}"
#
#
#  - command: >
#      ssh -o BatchMode=yes -o StrictHostKeyChecking=no
#      cloud-user@{{item.server.private_v4}} true
#    register: result
#    until: result|success
#    retries: 10
#    delay: 5
#    with_items: "{{ newnodes.results }}"
#
#- hosts: "{{ group }}"
#  name: Install webserver
#
#  tasks:
#    - name: upload yum repo file to image
#      copy: src=local.repo dest=/etc/yum.repos.d/
#    - name: ensure apache is at the latest version
#      yum: name=httpd state=latest
#    - name: make sure apache is running
#      service: name=httpd state=running

